package ylss.model.table;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * ApplyOffer generated by hbm2java
 */
@Entity
@Table(name = "apply_offer", catalog = "ylss")
public class ApplyOffer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8519811621612413326L;
	private Integer applyId;
	private Integer offerId;
	private Integer doctorId;

	
	private Doctor doctor;
	
	private Offer offer;
	
	public ApplyOffer() {
	}

	public ApplyOffer(Integer offerId, Integer doctorId) {
		this.offerId = offerId;
		this.doctorId = doctorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ApplyId", unique = true, nullable = false)
	public Integer getApplyId() {
		return this.applyId;
	}

	public void setApplyId(Integer applyId) {
		this.applyId = applyId;
	}

	@Column(name = "OfferId")
	public Integer getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Integer offerId) {
		this.offerId = offerId;
	}

	@Column(name = "DoctorId")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@OneToOne
	@JoinColumn(name = "DoctorId",updatable=false,insertable=false)
	public Doctor getDoctor() {
		return doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}
	@OneToOne
	@JoinColumn(name = "OfferId",updatable=false,insertable=false)
	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

}
