package ylss.model.table;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

// Generated 2015-12-29 14:20:44 by Hibernate Tools 4.0.0

/**
 * CategoryT generated by hbm2java
 */
@Entity
@Table(name = "category_t", catalog = "ylss")
public class CategoryT implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1697953238910622289L;
	private Integer catId;
	private String parentId;
	private Integer childId;
	private Doctor doctor;
	private String isDel;
	private Date createTime;
	private String category;

	// private DoctorTypeT doctorTypeT;
	// private HospitalT hospitalT;
	// private KeShiT keShiT;

	public CategoryT() {
	}

	public CategoryT(Integer catId) {
		this.catId = catId;
	}

	public CategoryT(Integer catId, String parentId, Integer childId,
			Doctor doctor, String isDel, Date createTime, String category) {
		super();
		this.catId = catId;
		this.parentId = parentId;
		this.childId = childId;
		this.doctor = doctor;
		this.isDel = isDel;
		this.createTime = createTime;
		this.category = category;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "catId", length = 11)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "parentId", length = 32)
	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "childId", length = 19)
	public Integer getChildId() {
		return childId;
	}

	public void setChildId(Integer childId) {
		this.childId = childId;
	}

	@Column(name = "isDel")
	public String getIsDel() {
		return isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

	@Column(name = "createTime")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "category")
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@ManyToOne
	@JoinColumn(name = "childId", columnDefinition = "doctorId", insertable = false, updatable = false, nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	// @ManyToOne
	// @JoinColumn(name = "parentId", columnDefinition = "uid", insertable =
	// false, updatable = false, nullable = false)
	// public DoctorTypeT getDoctorTypeT() {
	// return this.doctorTypeT;
	// }
	//
	// public void setDoctorTypeT(DoctorTypeT doctorTypeT) {
	// this.doctorTypeT = doctorTypeT;
	// }
	//
	// @ManyToOne
	// @JoinColumn(name = "parentId", columnDefinition = "uid", insertable =
	// false, updatable = false, nullable = false)
	// public HospitalT getHospitalT() {
	// return this.hospitalT;
	// }
	//
	// public void setHospitalT(HospitalT hospitalT) {
	// this.hospitalT = hospitalT;
	// }
	//
	// @ManyToOne
	// @JoinColumn(name = "parentId", columnDefinition = "uid", insertable =
	// false, updatable = false, nullable = false)
	// public KeShiT getKeShiT() {
	// return this.keShiT;
	// }
	//
	// public void setKeShiT(KeShiT keShiT) {
	// this.keShiT = keShiT;
	// }

}
