package ylss.model.table;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "ylss")
public class Doctor implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3024604106971436949L;
	private int doctorId;
	private String doctorNumber;
	private String doctorType;
	private String status;
	private Date birthday;
	private String sex;
	private Integer qualification;// 临床经验
	private String qualificationNo;// 证书编号

	private String idCard;// 身份证
	private String department;// 科室
	private double starLevel = 0;
	private String hospital;// 医院

	private String specialty;// 专长
	private String alipayNo;

	private User user;
	private DoctorRealtimeInfo doctorRealtimeInfo;

	private Set<Order> orderList;
	private Set<Withdraw> withdraws;
	private Set<CategoryT> categoryTs;

	// private Set<CategoryT> categoryTs = new HashSet<CategoryT>(0);

	// , fetch = FetchType.EAGER, cascade = CascadeType.ALL

	@OneToMany(mappedBy = "doctorId")
	public Set<Order> getOrderList() {
		return orderList;
	}

	public void setOrderList(Set<Order> orderList) {
		this.orderList = orderList;
	}

	public Doctor() {
	}

	public Doctor(int doctorId) {
		this.doctorId = doctorId;
	}

	@JoinColumn(name = "DoctorId")
	@OneToOne
	@PrimaryKeyJoinColumn
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@JoinColumn(name = "DoctorId")
	@OneToOne
	@PrimaryKeyJoinColumn
	public DoctorRealtimeInfo getDoctorRealtimeInfo() {
		return doctorRealtimeInfo;
	}

	public void setDoctorRealtimeInfo(DoctorRealtimeInfo doctorRealtimeInfo) {
		this.doctorRealtimeInfo = doctorRealtimeInfo;
	}

	public Doctor(int doctorId, String doctorNumber, String doctorType,
			String status, Date birthday, String sex, Integer qualification,
			String qualificationNo, String idCard, String department,
			double starLevel, String hospital, String specialty,
			String alipayNo, User user, DoctorRealtimeInfo doctorRealtimeInfo,
			Set<Order> orderList, Set<Withdraw> withdraws) {
		super();
		this.doctorId = doctorId;
		this.doctorNumber = doctorNumber;
		this.doctorType = doctorType;
		this.status = status;
		this.birthday = birthday;
		this.sex = sex;
		this.qualification = qualification;
		this.qualificationNo = qualificationNo;
		this.idCard = idCard;
		this.department = department;
		this.starLevel = starLevel;
		this.hospital = hospital;
		this.specialty = specialty;
		this.alipayNo = alipayNo;
		this.user = user;
		this.doctorRealtimeInfo = doctorRealtimeInfo;
		this.orderList = orderList;
		this.withdraws = withdraws;
	}

	@Id
	@Column(name = "DoctorId", unique = true, nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "DoctorNumber", length = 12)
	public String getDoctorNumber() {
		return this.doctorNumber;
	}

	public void setDoctorNumber(String doctorNumber) {
		this.doctorNumber = doctorNumber;
	}

	@Column(name = "DoctorType", length = 7)
	public String getDoctorType() {
		return this.doctorType;
	}

	public void setDoctorType(String doctorType) {
		this.doctorType = doctorType;
	}

	@Column(name = "Status", length = 12)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "Birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Sex", length = 5)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "QualificationNo", length = 40)
	public String getQualificationNo() {
		return this.qualificationNo;
	}

	public void setQualificationNo(String qualificationNo) {
		this.qualificationNo = qualificationNo;
	}

	@Column(name = "IdCard", length = 18)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "Department", length = 32)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "StarLevel")
	public double getStarLevel() {
		return this.starLevel;
	}

	public void setStarLevel(double starLevel) {
		this.starLevel = starLevel;
	}

	@Column(name = "Hospital", length = 32)
	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	@Column(name = "Qualification", length = 32)
	public Integer getQualification() {
		return this.qualification;
	}

	public void setQualification(Integer qualification) {
		this.qualification = qualification;
	}

	@Column(name = "Specialty")
	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	@Column(name = "AlipayNo", length = 100)
	public String getAlipayNo() {
		return alipayNo;
	}

	public void setAlipayNo(String alipayNo) {
		this.alipayNo = alipayNo;
	}

	@OneToMany(mappedBy = "doctorId")
	public Set<Withdraw> getWithdraws() {
		return this.withdraws;
	}

	public void setWithdraws(Set<Withdraw> withdraws) {
		this.withdraws = withdraws;
	}

	@OneToMany(mappedBy = "parentId")
	public Set<CategoryT> getCategoryTs() {
		return categoryTs;
	}

	public void setCategoryTs(Set<CategoryT> categoryTs) {
		this.categoryTs = categoryTs;
	}

}
