package ylss.model.table;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import ylss.model.constant.databaseConstant.DoctorServiceStatus;

/**
 * DoctorRealtimeInfo generated by hbm2java
 */
@Entity
@Table(name = "doctor_realtime_info", catalog = "ylss")
public class DoctorRealtimeInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5969042860059931221L;
	private Integer doctorId;
	private Double longitude;
	private Double latitude;
	private String serviceStatus = DoctorServiceStatus.close;
	private Integer serviceCount = 0;
	private Doctor doctor;

	public DoctorRealtimeInfo(Integer doctorId, Double longitude, Double latitude, String serviceStatus,
			Integer serviceCount, Doctor doctor) {
		super();
		this.doctorId = doctorId;
		this.longitude = longitude;
		this.latitude = latitude;
		this.serviceStatus = serviceStatus;
		this.serviceCount = serviceCount;
		this.doctor = doctor;
	}

	@OneToOne
	@JoinColumn(name = "DoctorId", nullable = false, insertable = false, updatable = false)
	public Doctor getDoctor() {
		return doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public DoctorRealtimeInfo() {
	}

	public DoctorRealtimeInfo(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Id
	@Column(name = "DoctorId", unique = true, nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "Longitude", precision = 10, scale = 6)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "Latitude", precision = 10, scale = 6)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "ServiceStatus", length = 5)
	public String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	@Column(name = "ServiceCount")
	public Integer getServiceCount() {
		return this.serviceCount;
	}

	public void setServiceCount(Integer serviceCount) {
		this.serviceCount = serviceCount;
	}

}
