package ylss.model.table;

// Generated 2015-12-29 9:19:15 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * DoctorTypeT generated by hbm2java
 */
@Entity
@Table(name = "doctor_type_t", catalog = "ylss", uniqueConstraints = @UniqueConstraint(columnNames = "uid"))
public class DoctorTypeT implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5819709924437584703L;

	private Integer dtId;
	private String uid;
	private String doctorType;
	private Date createTime;
	private String isDel;

	// private Set<CategoryT> categoryTs;

	// private Set<CategoryT> categoryTs = new HashSet<CategoryT>(0);

	public DoctorTypeT() {
	}

	public DoctorTypeT(String uid) {
		this.uid = uid;
	}

	public DoctorTypeT(Integer dtId, String uid, String doctorType,
			Date createTime, String isDel) {
		super();
		this.dtId = dtId;
		this.uid = uid;
		this.doctorType = doctorType;
		this.createTime = createTime;
		this.isDel = isDel;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "dtId", unique = true, nullable = false)
	public Integer getDtId() {
		return this.dtId;
	}

	public void setDtId(int dtId) {
		this.dtId = dtId;
	}

	@Column(name = "uid", unique = true, nullable = false)
	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "doctorType")
	public String getDoctorType() {
		return this.doctorType;
	}

	public void setDoctorType(String doctorType) {
		this.doctorType = doctorType;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@Column(name = "createTime", length = 19)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "isDel")
	public String getIsDel() {
		return isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

	// @OneToMany(mappedBy = "parentId")
	// public Set<CategoryT> getCategoryTs() {
	// return categoryTs;
	// }
	//
	// public void setCategoryTs(Set<CategoryT> categoryTs) {
	// this.categoryTs = categoryTs;
	// }

}
