package ylss.model.table;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "ylss")
public class Feedback implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7765585902818318402L;
	private int adviceId;
	private String contactWay="";
	private String adviceContent="";

	public Feedback() {
	}

	public Feedback(int adviceId) {
		this.adviceId = adviceId;
	}

	public Feedback(int adviceId, String contactWay, String adviceContent) {
		this.adviceId = adviceId;
		this.contactWay = contactWay;
		this.adviceContent = adviceContent;
	}

	@Id
	@Column(name = "AdviceId", unique = true, nullable = false)
	public int getAdviceId() {
		return this.adviceId;
	}

	public void setAdviceId(int adviceId) {
		this.adviceId = adviceId;
	}


	@Column(name = "ContactWay", length = 256)
	public String getContactWay() {
		return this.contactWay;
	}

	public void setContactWay(String contactWay) {
		this.contactWay = contactWay;
	}

	@Column(name = "AdviceContent", length = 1024)
	public String getAdviceContent() {
		return this.adviceContent;
	}

	public void setAdviceContent(String adviceContent) {
		this.adviceContent = adviceContent;
	}


}
