package ylss.model.table;

// Generated 2015-12-29 14:20:44 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IllnessT generated by hbm2java
 */
@Entity
@Table(name = "illness_t", catalog = "ylss", uniqueConstraints = @UniqueConstraint(columnNames = "uid"))
public class IllnessT implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1843885343654950161L;

	private int ilId;
	private String uid;
	private String illness;
	private Date createTime;
	private String isDel;

	public IllnessT() {
	}

	public IllnessT(int ilId, String uid) {
		this.ilId = ilId;
		this.uid = uid;
	}

	public IllnessT(int ilId, String uid, String illness, Date createTime,
			String isDel) {
		super();
		this.ilId = ilId;
		this.uid = uid;
		this.illness = illness;
		this.createTime = createTime;
		this.isDel = isDel;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ilId", length = 11)
	public int getIlId() {
		return this.ilId;
	}

	public void setIlId(int ilId) {
		this.ilId = ilId;
	}

	@Column(name = "uid", unique = true, nullable = false)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "illness")
	public String getIllness() {
		return this.illness;
	}

	public void setIllness(String illness) {
		this.illness = illness;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "isDel")
	public String getIsDel() {
		return isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

}
