package ylss.model.table;

// Generated 2015-12-29 14:20:44 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * KeShiT generated by hbm2java
 */
@Entity
@Table(name = "ke_shi_t", catalog = "ylss", uniqueConstraints = @UniqueConstraint(columnNames = "uid"))
public class KeShiT implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3869260562795594554L;

	private Integer keShiId;
	private String uid;
	private String keShi;
	private String isDel;
	private Date createTime;

	// private Set<CategoryT> categoryTs;

	public KeShiT() {
	}

	public KeShiT(String uid) {
		this.uid = uid;
	}

	public KeShiT(Integer keShiId, String uid, String keShi, String isDel) {
		super();
		this.keShiId = keShiId;
		this.uid = uid;
		this.keShi = keShi;
		this.isDel = isDel;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "keShiId", unique = true, nullable = false)
	public Integer getKeShiId() {
		return this.keShiId;
	}

	public void setKeShiId(Integer keShiId) {
		this.keShiId = keShiId;
	}

	@Column(name = "uid", unique = true, nullable = false)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "keShi")
	public String getKeShi() {
		return this.keShi;
	}

	public void setKeShi(String keShi) {
		this.keShi = keShi;
	}

	@Column(name = "isDel")
	public String getIsDel() {
		return isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	// @OneToMany(mappedBy = "parentId")
	// public Set<CategoryT> getCategoryTs() {
	// return this.categoryTs;
	// }
	//
	// public void setCategoryTs(Set<CategoryT> categoryTs) {
	// this.categoryTs = categoryTs;
	// }

}
