package ylss.model.table;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer", catalog = "ylss")
public class Offer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1149309138764828037L;
	private Integer offerId;
	private String name;
	private String phoneNo;
	private String requirement;
	private String hospital;
	private String status;
	private Date endTime = new Date();

	public Offer(Integer offerId, String name, String phoneNo,
			String requirement, String hospital, String status, Date endTime) {
		super();
		this.offerId = offerId;
		this.name = name;
		this.phoneNo = phoneNo;
		this.requirement = requirement;
		this.hospital = hospital;
		this.status = status;
		this.endTime = endTime;
	}

	public Offer() {
	}

	public Offer(Integer offerId) {
		this.offerId = offerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OfferId", unique = true, nullable = false)
	public Integer getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Integer offerId) {
		this.offerId = offerId;
	}

	@Column(name = "Name", length = 64)
	@NotNull(message = "姓名不能为空")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PhoneNo", length = 11)
	@NotNull(message = "手机号不能为空")
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "Requirement", length = 255)
	public String getRequirement() {
		return this.requirement;
	}

	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

	@Column(name = "Hospital", length = 128)
	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	// @DateTimeFormat(pattern = "yyyy-MM-ddThh:mm")
	// @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
