package ylss.model.table;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "ylss")
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2778510940035528520L;
	private Integer orderId;
	private Integer patientId;
	private Integer doctorId;
	private Integer patientInfoId;
	private String illnessDesc;
	private Date serviceTime;
	private String status;
	private Double patientPayMoney;
	private Double doctorGetMoney;

	private String checkResult = "";
	private String prescription = "";

	private String evaluation;
	private Integer starLevel;
	private Integer orderType;

	private Date createTime = new Date();
	private Date finishTime;
	private Date statusTime;
	private Doctor doctor;
	private String reason;
	// private PatientInfo patientInfo;

	private User patient;

	public Order(Integer orderId, Integer patientId, Integer doctorId,
			Integer patientInfoId, String illnessDesc, Date serviceTime,
			String status, Double patientPayMoney, Double doctorGetMoney,
			String checkResult, String prescription, String evaluation,
			Integer starLevel, Integer orderType, Date createTime,
			Date finishTime, Date statusTime, Doctor doctor, String reason,
			User patient) {
		super();
		this.orderId = orderId;
		this.patientId = patientId;
		this.doctorId = doctorId;
		this.patientInfoId = patientInfoId;
		this.illnessDesc = illnessDesc;
		this.serviceTime = serviceTime;
		this.status = status;
		this.patientPayMoney = patientPayMoney;
		this.doctorGetMoney = doctorGetMoney;
		this.checkResult = checkResult;
		this.prescription = prescription;
		this.evaluation = evaluation;
		this.starLevel = starLevel;
		this.orderType = orderType;
		this.createTime = createTime;
		this.finishTime = finishTime;
		this.statusTime = statusTime;
		this.doctor = doctor;
		this.reason = reason;
		this.patient = patient;
	}

	public Order() {
	}

	public Order(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "Reason")
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Id
	@Column(name = "OrderId", unique = true, nullable = false)
	@GeneratedValue(strategy = IDENTITY)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "PatientId")
	@NotNull(message = "patientId 不能为空")
	public Integer getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

	@NotNull(message = "doctorId 不能为空")
	@Column(name = "DoctorId")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "PatientInfoId")
	public Integer getPatientInfoId() {
		return this.patientInfoId;
	}

	public void setPatientInfoId(Integer patientInfoId) {
		this.patientInfoId = patientInfoId;
	}

	@Column(name = "IllnessDesc", length = 1024)
	public String getIllnessDesc() {
		return this.illnessDesc;
	}

	public void setIllnessDesc(String illnessDesc) {
		this.illnessDesc = illnessDesc;
	}

	@Column(name = "DoctorGetMoney", precision = 10)
	public Double getDoctorGetMoney() {
		return this.doctorGetMoney;
	}

	public void setDoctorGetMoney(Double doctorGetMoney) {
		this.doctorGetMoney = doctorGetMoney;
	}

	@Column(name = "PatientPayMoney", precision = 10)
	public Double getPatientPayMoney() {
		return this.patientPayMoney;
	}

	public void setPatientPayMoney(Double patientPayMoney) {
		this.patientPayMoney = patientPayMoney;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
	@NotNull(message = "serviceTime 不能为空")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ServiceTime", length = 19)
	public Date getServiceTime() {
		return this.serviceTime;
	}

	public void setServiceTime(Date serviceTime) {
		this.serviceTime = serviceTime;
	}

	@Column(name = "Status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "checkResult", length = 1024)
	public String getCheckResult() {
		return checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}

	@Column(name = "Prescription", length = 1024)
	public String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(String prescription) {
		this.prescription = prescription;
	}

	@Column(name = "Evaluation")
	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

	@Column(name = "starLevel")
	public Integer getStarLevel() {
		return starLevel;
	}

	public void setStarLevel(Integer starLevel) {
		this.starLevel = starLevel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FinishTime", length = 19)
	public Date getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	@ManyToOne
	@JoinColumn(name = "DoctorId", nullable = false, insertable = false, updatable = false)
	public Doctor getDoctor() {
		return doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne
	@JoinColumn(name = "PatientId", referencedColumnName = "UserId", nullable = false, insertable = false, updatable = false)
	public User getPatient() {
		return patient;
	}

	public void setPatient(User patient) {
		this.patient = patient;
	}

	// @ManyToOne
	// @JoinColumn(name = "PatientInfoId", referencedColumnName = "InfoId",
	// nullable = false, insertable = false, updatable = false)
	// public PatientInfo getPatientInfo() {
	// return patientInfo;
	// }
	//
	// public void setPatientInfo(PatientInfo patientInfo) {
	// this.patientInfo = patientInfo;
	// }

	@Column(name = "orderType")
	@NotNull(message = "orderType 不能为空")
	public Integer getOrderType() {
		return orderType;
	}

	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusTime", length = 19)
	public Date getStatusTime() {
		return statusTime;
	}

	public void setStatusTime(Date statusTime) {
		this.statusTime = statusTime;
	}

}
