package ylss.model.table;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 2015-7-17 14:01:14 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.google.common.collect.Lists;

import ylss.model.constant.UtilConstant;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "ylss", uniqueConstraints = @UniqueConstraint(columnNames = "PhoneNo"))
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1012085713958444391L;
	private Integer userId;
	private String phoneNo;
	private Boolean haveIcon = false;
	private String userName;
	private String password;
	private String validateCode;
	private String userType;
	private String status = "able";
	private String token;
	private String clientId;
	private String deviceToken;
	private String platform;
	private String attribution;

	private Date lockTime = new Date(UtilConstant.aDateLongAgo);
	private Date tokenValidDate;
	private Date createTime = new Date();

	private List<AccountOperateHistory> accountOperateHistories;

	private Account account;

	public User(Integer userId, String phoneNo, Boolean haveIcon,
			String userName, String password, String validateCode,
			String userType, String status, String token, String clientId,
			String deviceToken, String platform, String attribution,
			Date lockTime, Date tokenValidDate, Date createTime,
			List<AccountOperateHistory> accountOperateHistories, Account account) {
		super();
		this.userId = userId;
		this.phoneNo = phoneNo;
		this.haveIcon = haveIcon;
		this.userName = userName;
		this.password = password;
		this.validateCode = validateCode;
		this.userType = userType;
		this.status = status;
		this.token = token;
		this.clientId = clientId;
		this.deviceToken = deviceToken;
		this.platform = platform;
		this.attribution = attribution;
		this.lockTime = lockTime;
		this.tokenValidDate = tokenValidDate;
		this.createTime = createTime;
		this.accountOperateHistories = accountOperateHistories;
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", length = 19)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public User() {
	}

	public User(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UserId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "PhoneNo", unique = true, nullable = false, length = 11)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "HaveIcon")
	public Boolean getHaveIcon() {
		return this.haveIcon;
	}

	public void setHaveIcon(Boolean haveIcon) {
		this.haveIcon = haveIcon;
	}

	@Column(name = "UserName", length = 32)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ValidateCode", length = 32)
	public String getValidateCode() {
		return this.validateCode;
	}

	public void setValidateCode(String validateCode) {
		this.validateCode = validateCode;
	}

	@Column(name = "UserType", length = 8)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "Status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LockTime", length = 19)
	public Date getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	@Column(name = "Token", length = 68)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TokenValidDate", length = 19)
	public Date getTokenValidDate() {
		return this.tokenValidDate;
	}

	public void setTokenValidDate(Date tokenValidDate) {
		this.tokenValidDate = tokenValidDate;
	}

	@Column(name = "ClientID", length = 50)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@OneToMany(mappedBy = "userId")
	public List<AccountOperateHistory> getOperateHistories() {
		if (accountOperateHistories == null
				|| accountOperateHistories.size() < 2) {
			return accountOperateHistories;
		}

		return Lists.reverse(accountOperateHistories);
	}

	public void setOperateHistories(
			List<AccountOperateHistory> operateHistorySet) {
		this.accountOperateHistories = operateHistorySet;
	}

	@OneToOne
	@PrimaryKeyJoinColumn
	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "DeviceToken", length = 70)
	public String getDeviceToken() {
		return deviceToken;
	}

	public void setDeviceToken(String deviceToken) {
		this.deviceToken = deviceToken;
	}

	@Column(name = "Platform", length = 20)
	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "Attribution")
	public String getAttribution() {
		return attribution;
	}

	public void setAttribution(String attribution) {
		this.attribution = attribution;
	}

}
