package ylss.model.table;

// Generated 2015-7-13 17:34:27 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Withdraw generated by hbm2java
 */
@Entity
@Table(name = "withdraw", catalog = "ylss")
public class Withdraw implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8296287755435359131L;
	private Integer withdrawId;
	private int doctorId;
	private double money;
	private String status;
	private Date createTime = new Date();
	private Date updateTime;

	private Doctor doctor;

	public Withdraw() {
	}

	public Withdraw(int doctorId, double money, String status) {
		this.doctorId = doctorId;
		this.money = money;
		this.status = status;
	}

	public Withdraw(int doctorId, double money, String status, Date createTime,
			Date updateTime) {
		this.doctorId = doctorId;
		this.money = money;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "WithdrawId", unique = true, nullable = false)
	public Integer getWithdrawId() {
		return this.withdrawId;
	}

	public void setWithdrawId(Integer withdrawId) {
		this.withdrawId = withdrawId;
	}

	@Column(name = "DoctorId", nullable = false, updatable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "Money", nullable = false, precision = 20)
	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	@Column(name = "Status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@ManyToOne
	@JoinColumn(name = "DoctorId", nullable = false, insertable = false, updatable = false)
	public Doctor getDoctor() {
		return doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

}
